Repos/WMSGlobalReportPortal/WMS.Global.Portal/Controllers/MapController.cs
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using NBK.AuthServiceUtil;
using WMS.Global.Portal.Models;
using WMS.Global.Portal.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using NBK.ECService.WMSReport.DTO;

namespace WMS.Global.Portal.Controllers
{
    [Authorize]
    public class MapController : BaseController
    {
        #region 仓库业务分部
        /// <summary>
        /// 仓库业务分部
        /// </summary>
        /// <returns></returns>
        public ActionResult HistoryServiceStation()
        {
            return View();
        }


        /// <summary>
        /// 获取仓库业务数据
        /// </summary>
        /// <returns></returns>
        public ActionResult GetHistoryServiceStationData(int page)
        {
            var rsp = HomeApiClient.GetInstance().GetHistoryServiceStationData(page);
            if (rsp.Success)
            {
                return Json(new { success = true, data = rsp.ResponseResult, message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion


        /// <summary>
        /// 最近仓库发货
        /// </summary>
        /// <returns></returns>
        public ActionResult RealTimeDelivery()
        {
            return View();
        }


        #region 仓库业务分部
        /// <summary>
        /// 仓库服务站关系图
        /// </summary>
        /// <returns></returns>
        public ActionResult WarehouseStationRelation()
        {
            return View();
        }

        public ActionResult GetWarehouseStationRelation()
        {
            var rsp = HomeApiClient.GetInstance().GetWarehouseStationRelation();
            if (rsp.Success)
            {
                return Json(new { success = true, data = rsp.ResponseResult, message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);

            }
        }
        #endregion

        /// <summary>
        /// 仓库日历订单
        /// </summary>
        /// <returns></returns>
        public ActionResult CalendarOrder()
        {
            ViewBag.Month = DateTime.Now.Month;
            ViewBag.Year = DateTime.Now.Year;
            return View();
        }


        /// <summary>
        /// 每日出入库统计
        /// </summary>
        /// <returns></returns>
        public ActionResult GetDailyEventDataCountInfo(string startDate, string endDate)
        {
            var rsp = HomeApiClient.GetInstance().GetDailyEventDataCountInfo(startDate, endDate);
            if (rsp.Success && rsp.ResponseResult != null)
            {
                return Json(new { Success = true, Data = rsp.ResponseResult }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CalendarDataByDate(string date)
        {
            var rsp = HomeApiClient.GetInstance().GetCalendarDataByDate(date);

            var model = new List<CalendarDataByDateDto>();
            if (rsp.Success && rsp.ResponseResult != null)
            {
                model = rsp.ResponseResult;
            }
            return View(model);
        }


        #region 仓库作业时间统计
        /// <summary>
        /// 仓库作业时间分布和仓库作业类型时间分布
        /// </summary>
        /// <returns></returns>
        public ActionResult WorkDistribution()
        {
            return View();
        }
        /// <summary>
        /// 获取数据
        /// </summary>
        /// <returns></returns>
        public ActionResult GetWorkDistributionData()
        {
            var rsp = HomeApiClient.GetInstance().GetWorkDistributionData();
            if (rsp.Success)
            {
                return Json(new { success = true, data = rsp.ResponseResult, message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetWorkDistributionByWarehouse(Guid sysId, int index)
        {
            var rsp = HomeApiClient.GetInstance().GetWorkDistributionByWarehouse(sysId);
            if (rsp.Success)
            {
                return Json(new { success = true, data = rsp.ResponseResult, index = index, message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult GetWorkDistributionPieData()
        {
            var rsp = HomeApiClient.GetInstance().GetWorkDistributionPieData();
            if (rsp.Success)
            {
                return Json(new { success = true, data = rsp.ResponseResult, message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

    }
}

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_Aside.cshtml
@using NBK.ECService.WMSReport.DTO.Base
@using WMS.Global.Portal.Controllers
@using WMS.Global.Portal
@using System.Security.Claims
@using NBK.AuthServiceUtil
@using WMS.Global.Portal.Helpers

<aside id="left-panel">
    @{ Html.RenderPartial("_CurrentUser"); }
    <nav>
        <ul>
            @{
                List<MenuDto> menuList = BaseController.GetSystemMenu(User.Identity.Name);
                if (menuList == null || menuList.Count == 0)
                {
                    Response.Redirect("/Account/LogOut");
                }
                var mainMenuList = menuList.Where(p => p.ParentSysId.HasValue == false).ToList();
                foreach (var mainMenuItem in mainMenuList.OrderBy(p => p.SortSequence))
                {
                    <li class="@Html.RouteIf(mainMenuItem.Controller,"", "active")">
                        <a href="#">
                            <i class="fa fa-lg fa-fw @Html.Raw(mainMenuItem.ICons)"></i>
                            <span class="menu-item-parent">@mainMenuItem.MenuName</span>
                        </a>

                        <ul>
                            @{
                                var subMenuList = menuList.Where(p => p.ParentSysId == mainMenuItem.SysId);
                                if (subMenuList != null)
                                {
                                    foreach (var subMenuItem in subMenuList.ToList().OrderBy(p => p.SortSequence))
                                    {
                                        <li class="@Html.RouteIf(subMenuItem.Action,subMenuItem.Controller,"active")" title="@subMenuItem.MenuName">
                                            <a href="@Url.Action(subMenuItem.Action, subMenuItem.Controller)">
                                                @subMenuItem.MenuName
                                            </a>
                                        </li>
                                    }
                                }

                            }
                        </ul>
                    </li>
                                }
            }
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>

<script>
    //<!-- ADD THE FATHER MENU ACTIVE BY THE SON MENU WHICH WAS SELECTED-->
    $(document).ready(function () {
        if ($("#left-panel>nav>ul>li>ul>li.active").length > 0) {
            if ($("#left-panel>nav>ul>li>ul>li.active").parent("ul").parent("li").length > 0) {
                $("#left-panel>nav>ul>li>ul>li.active").parent("ul").parent("li").addClass("active");
            }
        }
    });

</script>
<!-- END NAVIGATION -->

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_CurrentUser.cshtml
@using NBK.AuthServiceUtil
@using System.Security.Claims
<div class="login-info">
    <span>
        <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
            <img src="~/content/img/avatars/sunny.png" alt="me" class="online" />
            <span>
                @{
                    var loginUser = (HttpContext.Current.User.Identity as ClaimsIdentity).Claims.FirstOrDefault(p => p.Type.Equals(SystemDataConst.SessionLoginDisplayUserName, StringComparison.OrdinalIgnoreCase));
                    if (loginUser != null)
                    {
                        @loginUser.Value.ToString();
                    }
                } 
            </span>
            <i class="fa fa-angle-down"></i>
        </a>
    </span>
</div>

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_Footer.cshtml
    <!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">WMS Group Report <span class="hidden-xs"> - Web Application Framework</span> © 2011-2016</span>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_Header.cshtml
    <!-- HEADER -->
<header id="header">
    <div id="logo-group">
        <!-- PLACE YOUR LOGO HERE -->
        <span id="logo">
            <a href="/Home/Index"><p class="pname">WMS</p></a>
            <p class="pdesc">Global Report</p>
        </span>
        <!-- END LOGO PLACEHOLDER -->
    </div>
    <section id="top-right">

        <div class="pull-right">
            @Html.Partial("_TopRight")
        </div>

    </section>
</header>
<!-- END HEADER -->

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="@ViewBag.PageId" class="@Settings.CurrentTheme">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title> WMS Global.Report| @ViewBag.Title </title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!-- Basic Styles -->
    @Styles.Render("~/content/smartadmin")
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/content/img/favicon/favicon.ico" type="image/x-icon">

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700">

    <!-- Specifying a Webpage Icon for Web Clip
         Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/content/img/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/content/img/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/content/img/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/content/img/splash/touch-icon-ipad-retina.png">

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
    <link rel="apple-touch-startup-image" href="~/content/img/splash/iphone.png" media="screen and (max-device-width: 320px)">
    <script src="~/Scripts/libs/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/libs/jquery-ui-1.10.3.min.js"></script>

    @Scripts.Render("~/Scripts/plugin/echarts/echarts.min.js")
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Scripts.Render("~/plugins/sweetAlert")
</head>
<body class="@ViewBag.PageClass @Settings.CurrentTheme minified">
    @{ Html.RenderPartial("_Header", RenderSection("topright", false)); }
    @{ Html.RenderPartial("_Aside"); }
    <div id="main" role="main">
        @{ Html.RenderPartialIf("_Ribbon", Request.IsAuthenticated); }
        @RenderBody()
    </div>
    @{
        Html.RenderPartial("_Footer");
        Html.RenderPartial("_Tiles", Settings.EnableTiles);
    }
    @{ Html.RenderPartial("_Scripts", RenderSection("pagespecific", false)); }

    @RenderSection("scripts", required: false)
</body>

</html>

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_Scripts.cshtml
<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="~/Scripts/libs/jquery-2.1.1.min.js"></script>
<script src="~/Scripts/libs/jquery-ui-1.10.3.min.js"></script>
<!-- IMPORTANT: SmartAdmin Core -->
@Scripts.Render("~/scripts/smartadmin")

@if (Request.IsAuthenticated)
{
    <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
    <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/scripts/plugin/pace/pace.min.js"></script>
    <!-- Demo purpose only! -->
    <script src="/scripts/demo.min.js"></script>
}

<!-- Voice command : plugin -->
<script src="~/scripts/speech/voicecommand.min.js"></script>
<script src="~/Scripts/Utility/Extend.js?v1.0"></script>
<!-- SmartChat UI : plugin -->
@Scripts.Render("~/scripts/smart-chat")

<!-- DataTables : plugin -->
@Scripts.Render("~/scripts/datatables")

<!-- jQGrid : plugin -->
@Scripts.Render("~/scripts/jq-grid")

<!-- Forms : plugin -->
@Scripts.Render("~/scripts/forms")

<!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip, Morris, Sparkline, EasyPie -->
@Scripts.Render("~/scripts/charts")

<!-- Vector Maps Plugin: Vectormap engine, Vectormap language -->
@Scripts.Render("~/scripts/vector-map")

<!-- Full Calendar -->
@Scripts.Render("~/scripts/full-calendar")


@Scripts.Render("~/scripts/common")
<script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
    });
</script>

@if (@Model is HelperResult)
{
    @Model
}
<!-- Your GOOGLE ANALYTICS CODE Below-->
@*<script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'xx-xxxxxxxx-x']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
    </script>*@

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_Tiles.cshtml
<div id="shortcut1" style="display:none">
    <ul>
        <li>
            <a href="@Url.Action("HistoryServiceStation", "Map")" id="toplione" class="jarvismetro-tile big-cubes bg-color-blue"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i><span>仓库业务分部 </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("WarehouseStationRelation", "Map")" id="toplitwo" class="jarvismetro-tile big-cubes bg-color-orangeDark"> <span class="iconbox"> <i class="fa fa-codepen fa-4x"></i> <span>仓库服务站关系</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("googlemap", "home")" class="jarvismetro-tile big-cubes bg-color-purple"> <span class="iconbox"> <i class="fa fa-map-marker fa-4x"></i> <span>Maps</span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("invoice", "misc")" class="jarvismetro-tile big-cubes bg-color-blueDark"> <span class="iconbox"> <i class="fa fa-book fa-4x"></i> <span>Invoice <span class="label pull-right bg-color-darken">99</span></span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("gallery", "appviews")" class="jarvismetro-tile big-cubes bg-color-greenLight"> <span class="iconbox"> <i class="fa fa-picture-o fa-4x"></i> <span>Gallery </span> </span> </a>
        </li>
        <li>
            <a href="@Url.Action("profile", "appviews")" class="jarvismetro-tile big-cubes bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>My Profile </span> </span> </a>
        </li>
    </ul>
</div>
<script>
    $(function () {
        $('.jarvismetro-tile').removeClass('selected');
        var test = window.location.pathname;
        if (test == "/Map/HistoryServiceStation") {
            $("#toplione").addClass('selected');
        }
        else if (test == "/Map/WarehouseStationRelation") {
            $("#toplitwo").addClass('selected');
        }

    });
</script>

Repos/WMSGlobalReportPortal/WMS.Global.Portal/Views/Shared/_TopRight.cshtml
<!-- collapse menu button -->
<div id="hide-menu" class="btn-header pull-right">
    <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
</div>
<!-- end collapse menu -->
<!-- #MOBILE -->
<!-- Top menu profile link : this shows only when top menu is active -->
<ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
    <li class="">
        <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
            <img src="~/content/img/avatars/sunny.png" alt="John Doe" class="online" />
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> Profile</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <>S</>hortcut</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <>S</>creen</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("Login", "Account")" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><>L</>ogout</strong></a>
            </li>
        </ul>
    </li>
</ul>

<!-- logout button -->
<div id="logout" class="btn-header transparent pull-right">
    <span> <a href="@Url.Action("login", "account")" title="Sign Out" data-action="userLogout" data-logout-msg=""><i class="fa fa-sign-out"></i></a> </span>
</div>
<!-- end logout button -->
<!-- search mobile button (this is hidden till mobile view port) -->
<div id="search-mobile" class="btn-header transparent pull-right">
    <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
</div>
<!-- end search mobile button -->
<!-- input: search field -->
<form action="@Url.Action("search", "misc")" class="header-search pull-right hidden">
    <input id="search-fld" type="text" name="param" placeholder="Find reports and more" data-autocomplete='["ActionScript","AppleScript","Asp","BASIC","C","C++","Clojure","COBOL","ColdFusion","Erlang","Fortran","Groovy","Haskell","Java","JavaScript","Lisp","Perl","PHP","Python","Ruby","Scala","Scheme"]'>
    <button type="submit">
        <i class="fa fa-search"></i>
    </button>
    <a href="javascript:void(0);" id="cancel-search-js" title="Cancel Search"><i class="fa fa-times"></i></a>
</form>
<!-- end input: search field -->
<!-- fullscreen button -->
<div id="fullscreen" class="btn-header transparent pull-right hidden">
    <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
</div>
<!-- end fullscreen button -->
<!-- #Voice Command: Start Speech -->
<div id="speech-btn" class="btn-header transparent pull-right hidden-sm hidden-xs hidden">
    <div>
        <a href="javascript:void(0)" title="Voice Command" data-action="voiceCommand"><i class="fa fa-microphone"></i></a>
        <div class="popover bottom">
            <div class="arrow"></div>
            <div class="popover-content">
                <h4 class="vc-title">Voice command activated <br><small>Please speak clearly into the mic</small></h4>
                <h4 class="vc-title-error text-center">
                    <i class="fa fa-microphone-slash"></i> Voice command failed
                    <br><small class="txt-color-red">Must <strong>"Allow"</strong> Microphone</small>
                    <br><small class="txt-color-red">Must have <strong>Internet Connection</strong></small>
                </h4>
                <a href="javascript:void(0);" class="btn btn-success" onclick="commands.help()">See Commands</a>
                <a href="javascript:void(0);" class="btn bg-color-purple txt-color-white" onclick="$('#speech-btn .popover').fadeOut(50);">Close Popup</a>
            </div>
        </div>
    </div>
</div>
<!-- end voice command -->
<!-- multiple lang dropdown : find all flags in the flags page -->
<ul class="header-dropdown-list hidden-xs hidden">
    <li>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="~/content/img/blank.gif" class="flag flag-us" alt="United States"> <span> English (US) </span> <i class="fa fa-angle-down"></i> </a>
        <ul class="dropdown-menu pull-right">
            <li class="active">
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-us" alt="United States"> English (US)</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-fr" alt="France"> Français</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-es" alt="Spanish"> Español</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-de" alt="German"> Deutsch</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-jp" alt="Japan"> 日本語</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-cn" alt="China"> 中文</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-it" alt="Italy"> Italiano</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-pt" alt="Portugal"> Portugal</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-ru" alt="Russia"> Русский язык</a>
            </li>
            <li>
                <a href="javascript:void(0);"><img src="~/content/img/blank.gif" class="flag flag-kr" alt="Korea"> 한국어</a>
            </li>

        </ul>
    </li>
</ul>
<!-- end multiple lang -->