Repos/WMSPortal/NBK.WMS.Portal/Controllers/AssemblyController.cs
using NBK.ECService.WMS.Utility.Enum;
using NBK.ECService.WMS.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NBK.WMS.Portal.Services;
using FortuneLab.WebApiClient;
using NBK.ECService.WMS.DTO;

namespace NBK.WMS.Portal.Controllers
{
    [Authorize]
    public class AssemblyController : BaseController
    {
        public ActionResult AssemblyList()
        {
            return View();
        }

        public ActionResult GetAssemblyStatusList()
        {
            List<SelectListItem> statusList = new List<SelectListItem>();
            statusList.Add(new SelectListItem { Text = "请选择", Value = null });
            statusList.Add(new SelectListItem { Text = AssemblyStatus.New.ToDescription(), Value = ((int)AssemblyStatus.New).ToString() });
            statusList.Add(new SelectListItem { Text = AssemblyStatus.Assembling.ToDescription(), Value = ((int)AssemblyStatus.Assembling).ToString() });
            statusList.Add(new SelectListItem { Text = AssemblyStatus.Finished.ToDescription(), Value = ((int)AssemblyStatus.Finished).ToString() });
            //statusList.Add(new SelectListItem { Text = AssemblyOrderStatus.Voided.ToDescription(), Value = ((int)AssemblyOrderStatus.Voided).ToString() });
            return Json(new { Success = true, Data = statusList }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAssemblyList(AssemblyQuery assemblyQuery)
        {
            var rsp = VASApiClient.GetInstance().GetAssemblyList(LoginCoreQuery, assemblyQuery);
            if (rsp.Success && rsp.ResponseResult.TableResuls != null)
            {
                return Json(new
                {
                    rsp.ResponseResult.TableResuls.aaData,
                    rsp.ResponseResult.TableResuls.iTotalDisplayRecords,
                    rsp.ResponseResult.TableResuls.iTotalRecords,
                    rsp.ResponseResult.TableResuls.sEcho

                }, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        public ActionResult AssemblyView(Guid sysId)
        {
            ViewBag.PrintName = PublicConst.PrintSettingZS;
            ViewBag.SysId = sysId;
            ViewBag.CurrentUserName = CurrentUser.DisplayName;
            ViewBag.WarehouseSysId = CurrentUser.WarehouseSysId;
            return View();
        }

        public ActionResult GetAssemblyViewDtoById(Guid sysId)
        {
            var rsp = VASApiClient.GetInstance().GetAssemblyViewDtoById(LoginCoreQuery, sysId,CurrentUser.WarehouseSysId);
            if (rsp.Success && rsp.ResponseResult != null)
            {
                return Json(new { Success = true, Data = rsp.ResponseResult }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult PrintAssemblyRCMDPickDetail(Guid sysId)
        {
            var rsp = VASApiClient.GetInstance().UpdateAssemblyStatus(LoginCoreQuery, sysId, AssemblyStatus.Assembling, CurrentUser.UserId, CurrentUser.UserName,CurrentUser.WarehouseSysId);
            if (rsp.Success)
            {
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult CancelAssemblyPicking(Guid sysId)
        {
            var rsp = VASApiClient.GetInstance().CancelAssemblyPicking(LoginCoreQuery, sysId, CurrentUser.UserId, CurrentUser.UserName, CurrentUser.WarehouseSysId);
            if (rsp.Success)
            {
                return Json(new { Success = true, Message = "撤销领料成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult FinishAssemblyOrder(AssemblyFinishDto assemblyFinishDto)
        {
            var rsp = VASApiClient.GetInstance().FinishAssemblyOrder(LoginCoreQuery, assemblyFinishDto);
            if (rsp.Success)
            {
                return Json(new { Success = true, Message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AddAssembly()
        {
            return View();
        }

        public ActionResult GetSkuListForAssembly(AssemblySkuQuery request)
        {
            var rsp = VASApiClient.GetInstance().GetSkuListForAssembly(request, LoginCoreQuery);
            if (rsp.ResponseResult.TableResuls != null)
            {
                return Json(new
                {
                    rsp.ResponseResult.TableResuls.aaData,
                    rsp.ResponseResult.TableResuls.iTotalDisplayRecords,
                    rsp.ResponseResult.TableResuls.iTotalRecords,
                    rsp.ResponseResult.TableResuls.sEcho

                }, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        public ActionResult AddAssemblyService(AddAssemblyDto request)
        {
            var rsp = VASApiClient.GetInstance().AddAssembly(request, LoginCoreQuery);
            if (rsp.Success)
            {
                return Json(new { Success = true, Message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetWeighSkuListForAssembly(AssemblyWeightSkuQuery request)
        {
            var rsp = VASApiClient.GetInstance().GetWeighSkuListForAssembly(request, LoginCoreQuery);
            if (rsp.ResponseResult.TableResuls != null)
            {
                return Json(new
                {
                    rsp.ResponseResult.TableResuls.aaData,
                    rsp.ResponseResult.TableResuls.iTotalDisplayRecords,
                    rsp.ResponseResult.TableResuls.iTotalRecords,
                    rsp.ResponseResult.TableResuls.sEcho

                }, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        public ActionResult SaveAssemblySkuWeight(AssemblyWeightSkuRequest request)
        {
            var rsp = VASApiClient.GetInstance().SaveAssemblySkuWeight(request, LoginCoreQuery);
            if (rsp.Success)
            {
                return Json(new { Success = true, Message = "操作成功" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetInventoryList(RFInventoryQuery request)
        {
            var rsp = VASApiClient.GetInstance().GetInventoryList(LoginCoreQuery, request);
            if (rsp.Success && rsp.ResponseResult != null)
            {
                return Json(new { Success = true, Data = rsp.ResponseResult }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult LocIsExist(LocationQuery request)
        {
            var rsp = VASApiClient.GetInstance().LocIsExist(LoginCoreQuery, request);
            if (rsp.Success && rsp.ResponseResult != null)
            {
                if (rsp.ResponseResult.IsSucess)
                {
                    return Json(new { Success = true, Data = rsp.ResponseResult }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Success = false, Message = rsp.ResponseResult.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AssemblyScanPickDetail(RFAssemblyPickDetailDto request)
        {
            var rsp = VASApiClient.GetInstance().AssemblyScanPickDetail(LoginCoreQuery, request);
            if (rsp.Success && rsp.ResponseResult != null)
            {
                if (rsp.ResponseResult.IsSucess)
                {
                    return Json(new { Success = true, Data = rsp.ResponseResult }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Success = false, Message = rsp.ResponseResult.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { Success = false, Message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AssemblyScanShelves(RFAssemblyScanShelvesDto request)
        {
            var rsp = VASApiClient.GetInstance().AssemblyScanShelves(LoginCoreQuery, request);
            if (rsp.Success && rsp.ResponseResult != null)
            {
                if (rsp.ResponseResult.IsSucess)
                {
                    return Json(new { Success = true, Data = rsp.ResponseResult }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Success = false, Message = rsp.ResponseResult.Message }, JsonRequestBehavior.AllowGet);
                }
            }
            else

Repos/WMSPortal/NBK.WMS.Portal/Views/Assembly/AssemblyList.cshtml
@using NBK.WMS.Portal.Helpers
@using NBK.AuthServiceUtil
@{
    ViewBag.Title = "生产加工单管理";
}

@Html.Breadcrumb("增值服务", "生产加工单管理")
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div id="div_AssemblyList" class="ibox-content m-b-sm border-bottom">
        <div class="row">
            <div class="col-sm-3">
                @Html.SearchTextBox("加工单号", "AssemblyOrderSearch")
            </div>
            <div class="col-sm-3">
                @Html.SearchTextBox("成品名称", "SkuNameSearch")
            </div>
            <div class="col-sm-3">
                @Html.SearchTextBox("成品UPC", "SkuUPCSearch")
            </div>
            <div class="col-sm-3">
                <label class="control-label">单据状态</label>
                <select id="StatusSearch" name="StatusSearch" class="form-control">
                    <option v-for="item in StatusList" v-bind:value="item.Value">{{ item.Text }}</option>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                @Html.DataPickerTextBox("计划加工日期", "PlanProcessingDateSearch")
            </div>
            <div class="col-sm-3">
                @Html.DataPickerTextBox("计划完工日期", "PlanCompletionDateSearch")
            </div>
            <div class="col-sm-3">
                @Html.DataPickerTextBox("实际加工日期", "ActualProcessingDateSearch")
            </div>
            <div class="col-sm-3">
                @Html.DataPickerTextBox("实际完工日期", "ActualCompletionDateSearch")
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                @Html.SearchTextBox("外部单据号", "ExternalOrderSearch")
            </div>
            <div class="col-sm-3">
                @Html.SearchTextBox("渠道", "Channel")
            </div>
            <div class="col-sm-1">
                <button id="btnSearch" class="btn btn-primary" type="button" v-on:click="search" style="margin-top:23px;float: left; ">查询</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content" style="overflow-x:auto">
                    <table id="gvAssembly" class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th data-data="AssemblyOrder">加工单号</th>
                                <th data-data="SkuName">成品名称</th>
                                <th data-data="StatusText">单据状态</th>
                                <th data-data="Channel">渠道</th>
                                <th data-data="PlanQty">计划加工数量</th>
                                <th data-data="ActualQty">实际加工数量</th>
                                <th data-data="PlanProcessingDateText">计划加工日期</th>
                                <th data-data="PlanCompletionDateText">计划完工日期</th>
                                <th data-data="ActualProcessingDateText">实际加工日期</th>
                                <th data-data="ActualCompletionDateText">实际完工日期</th>
                                <th data-data="ExternalOrder">外部单据号</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/dataPicker")
    <script src="~/Scripts/Utility/Common.js"></script>
    <script type="text/javascript">
        var AssemblyList = {
            statusVM: {},
            initData: function () {
                $.ajax({
                    url: "@Url.Action("GetAssemblyStatusList", "Assembly")",
                    type: "GET",
                    success: function (data) {
                        if (data.Success) {
                            AssemblyList.initVue(data.Data);
                        } else {
                            msgErro(data.Message);
                        }
                    }
                });
            },
            initVue: function (data) {
                this.statusVM = new Vue({
                    el: "#div_AssemblyList",
                    data: { StatusList: data },
                    methods: {
                        search: function () {
                            table.ajax.reload();
                        }
                    }
                });
            }
        }


        var table;
        $(document).ready(function () {
            $('#divPlanProcessingDateSearch .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            $('#divPlanCompletionDateSearch .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            $('#divActualProcessingDateSearch .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            $('#divActualCompletionDateSearch .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

            table = $('#gvAssembly').DataTable({
                "sAjaxSource": "/Assembly/GetAssemblyList",
                "fnServerParams": function (aoData) { //查询条件
                    aoData.push(
                        { "name": "AssemblyOrderSearch", "value": $("#AssemblyOrderSearch").val() },
                        { "name": "SkuNameSearch", "value": $("#SkuNameSearch").val() },
                        { "name": "SkuUPCSearch", "value": $("#SkuUPCSearch").val() },
                        { "name": "StatusSearch", "value": $("#StatusSearch").val() },
                        { "name": "PlanProcessingDateSearch", "value": $("#PlanProcessingDateSearch").val() },
                        { "name": "PlanCompletionDateSearch", "value": $("#PlanCompletionDateSearch").val() },
                        { "name": "ActualProcessingDateSearch", "value": $("#ActualProcessingDateSearch").val() },
                        { "name": "ActualCompletionDateSearch", "value": $("#ActualCompletionDateSearch").val() },
                        { "name": "ExternalOrderSearch", "value": $("#ExternalOrderSearch").val() },
                        { "name": "Channel", "value": $("#Channel").val() }
                    );
                },
                dom: 'Bfrtip',
                buttons: [
                    @if (AuthorizeManager.HasFunction(AuthKeyConst.VAS_Assembly_View, HttpContext.Current.User.Identity.Name))
                    {
                        <text>
                        {
                            text: '创建加工单',
                            action: function (e, dt, node, config) {
                                window.location.href = "/Assembly/AddAssembly";
                            }
                        }
                        </text>
                    }
                ],
                "columnDefs": [
                    {
                        "targets": 0,
                        "width": "15%",
                        render: function (data, type, full, meta) {
                            @if (AuthorizeManager.HasFunction(AuthKeyConst.VAS_Assembly_View, HttpContext.Current.User.Identity.Name))
                            {
                                <text>
                            return '<a target="_blank" href="/Assembly/AssemblyView?sysId=' + full.SysId + '">' + full.AssemblyOrder + '</a>';
                            </text>
                            }
                            else
                            {
                                <text>
                            return full.AssemblyOrder;
                            </text>
                            }
                        }
                    }
                ],
                "bServerSide": true,
                "bProcessing": true,
                "bPaginate": true, //翻页功能
                "bLengthChange": true, //改变每页显示数据数量
                "bFilter": false, //过滤功能
                "bSort": false, //排序功能
                "bInfo": true, //页脚信息
                "bAutoWidth": true, //自动宽度
                "aaSorting": [[2, "Asc"]],
                "oLanguage": {
                    "sLengthMenu": "每页显示 _MENU_ 条记录",
                    "sInfo": "从 _START_ 到 _END_ /共 _TOTAL_ 条数据",
                    "sInfoEmpty": "",
                    "sInfoFiltered": "(从 _MAX_ 条数据中检索)",
                    "oPaginate": {
                        "sFirst": "首页",
                        "sPrevious": "前一页",
                        "sNext": "后一页",
                        "sLast": "尾页"
                    },
                    "sZeroRecords": "没有检索到数据"
                }
            });

            AssemblyList.initData();
        });
    </script>
}