Repos/WMSPortal/NBK.WMS.Portal/Controllers/AjustmentController.cs
using NBK.AuthServiceUtil;
using NBK.ECService.WMS.DTO;
using NBK.ECService.WMS.Utility;
using NBK.ECService.WMS.Utility.Enum;
using NBK.WMS.Portal.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NBK.WMS.Portal.Controllers
{
    [Authorize]
    public class AjustmentController : BaseController
    {
        public ActionResult AjustmentMaintain()
        {
            return View();
        }

        public ActionResult GetAdjustmentListByPage(AdjustmentQuery request)
        {
            request.WarehouseSysId = CurrentUser.WarehouseSysId;
            var rsp = InventoryApiClient.GetInstance().GetAdjustmentListByPage(request, this.LoginCoreQuery);
            if (rsp.ResponseResult.TableResuls != null)
            {
                return Json(new
                {
                    rsp.ResponseResult.TableResuls.aaData,
                    rsp.ResponseResult.TableResuls.iTotalDisplayRecords,
                    rsp.ResponseResult.TableResuls.iTotalRecords,
                    rsp.ResponseResult.TableResuls.sEcho

                }, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        public ActionResult AjustmentView(Guid sysId)
        {
            var response = InventoryApiClient.GetInstance().GetAdjustmentBySysId(sysId, CurrentUser.WarehouseSysId, this.LoginCoreQuery);
            var model = new AdjustmentViewDto();
            if (response.Success)
            {
                model = response.ResponseResult;
            }
            ViewData["IsAuditDisplay"] = this.CheckHasAuthFun(AuthKeyConst.Inventory_Ajustment_Auditing)
                && (model.Status == (int)AdjustmentStatus.New);
            return View(model);
        }

        public ActionResult AddAjustment()
        {
            List<SelectListItem> warehouseList = new List<SelectListItem>();
            var rsp2 = InventoryApiClient.GetInstance().SelectItemWarehouse(LoginCoreQuery);
            if (rsp2.Success && rsp2.ResponseResult != null)
            {
                warehouseList.AddRange(rsp2.ResponseResult.Select(p => new SelectListItem
                {
                    Text = p.Text,
                    Value = p.Value
                }));
            }
            ViewBag.WarehouseList = warehouseList;
            ViewBag.WarehouseSysId = CurrentUser.WarehouseSysId;

            return View();
        }

        public ActionResult GetAdjustmentLevelSysCode()
        {
            List<SelectListItem> adjustmentLevelList = new List<SelectListItem>();

            var rsp = BaseDataApiClient.GetInstance().SelectItemSysCode("AdjustmentLevel");
            if (rsp.Success && rsp.ResponseResult != null)
            {
                adjustmentLevelList.AddRange(rsp.ResponseResult.Select(p => new SelectListItem
                {
                    Text = p.Text,
                    Value = p.Value
                }));
            }

            return Json(new { adjustmentLevelList }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddAjustmentService(AdjustmentDto dto)
        {
            dto.Type = (int)AdjustmentType.ProfiAndLoss;
            dto.CreateBy = CurrentUser.UserId;
            dto.CreateUserName = CurrentUser.DisplayName;
            dto.UpdateBy = CurrentUser.UserId;
            dto.UpdateUserName = CurrentUser.DisplayName;
            dto.AdjustmentDetailList.ForEach(p =>
            {
                p.CreateBy = CurrentUser.UserId;
                p.CreateUserName = CurrentUser.DisplayName;
                p.UpdateBy = CurrentUser.UserId;
                p.UpdateUserName = CurrentUser.DisplayName;
            });
            var rsp = InventoryApiClient.GetInstance().AddAdjustment(dto, this.LoginCoreQuery);

            if (rsp.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetSkuList(SkuInvLotLocLpnQuery skuQuery)
        {
            var rsp = InventoryApiClient.GetInstance().GetAdjustmentListByPage(skuQuery, LoginCoreQuery);
            if (rsp.Success && rsp.ResponseResult.TableResuls != null)
            {
                return Json(new
                {
                    rsp.ResponseResult.TableResuls.aaData,
                    rsp.ResponseResult.TableResuls.iTotalDisplayRecords,
                    rsp.ResponseResult.TableResuls.iTotalRecords,
                    rsp.ResponseResult.TableResuls.sEcho

                }, JsonRequestBehavior.AllowGet);
            }
            return null;
        }

        public ActionResult UpdateAjustment(Guid sysId)
        {
            var response = InventoryApiClient.GetInstance().GetAdjustmentBySysId(sysId, CurrentUser.WarehouseSysId, this.LoginCoreQuery);
            var model = new AdjustmentViewDto();
            if (response.Success)
            {
                model = response.ResponseResult;
            }
            ViewData["IsSaveDisplay"] = (model.Status == (int)AdjustmentStatus.New);
            return View(model);
        }

        public JsonResult UploadImage()
        {
            var file = Request.Files["file"];
            if (file != null)
            {
                var size = file.ContentLength;
                var type = Path.GetExtension(file.FileName);
                if (type != ".jpeg" && type != ".gif" && type != ".jpg" && type != ".png" && type != ".svg")
                {
                    return Json(new { Success = false, Message = "只能上传图片类型文件" }, JsonRequestBehavior.AllowGet);
                }
                var fileName = Guid.NewGuid() + type.ToLower();
                FileUploader.UploadFile(FileUploader.Adjustment, file.InputStream, fileName, FtpFileType.Image);
                return Json(new { Success = true, Name = file.FileName, Url = fileName, Size = size, Suffix = Path.GetExtension(file.FileName).ToLower(), ShowUrl = FileUploader.httpAddress + "/" + FileUploader.Adjustment + "/" + fileName }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Success = false, Message = "上传文件不能为空" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult UpdateAjustmentService(AdjustmentDto dto)
        {
            dto.Type = (int)AdjustmentType.ProfiAndLoss;
            dto.UpdateBy = CurrentUser.UserId;
            dto.UpdateUserName = CurrentUser.DisplayName;
            dto.AdjustmentDetailList.ForEach(p =>
            {
                p.UpdateBy = CurrentUser.UserId;
                p.UpdateUserName = CurrentUser.DisplayName;
            });

            var rsp = InventoryApiClient.GetInstance().UpdateAdjustment(dto, this.LoginCoreQuery);

            if (rsp.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult DeleteAjustmentSkus(string sysIdList)
        {
            var rsp = InventoryApiClient.GetInstance().DeleteAjustmentSkus(sysIdList.ToGuidList(),CurrentUser.WarehouseSysId, this.LoginCoreQuery);

            if (rsp.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Audit(AdjustmentAuditDto dto)
        {
            dto.AuditingBy = CurrentUser.UserId;
            dto.AuditingName = CurrentUser.DisplayName;
            dto.WarehouseSysId = CurrentUser.WarehouseSysId;
            var rsp = InventoryApiClient.GetInstance().Audit(dto, this.LoginCoreQuery);

            if (rsp.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Void(AdjustmentAuditDto dto)
        {
            dto.AuditingBy = CurrentUser.UserId;
            dto.AuditingName = CurrentUser.DisplayName;

            var rsp = InventoryApiClient.GetInstance().Void(dto, this.LoginCoreQuery);

            if (rsp.Success)
            {
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = rsp.ApiMessage.ErrorMessage }, JsonRequestBehavior.AllowGet); 
            }
        }
    }
}

Repos/WMSPortal/NBK.WMS.Portal/Views/Ajustment/AjustmentMaintain.cshtml
@using NBK.WMS.Portal.Helpers

@{
    ViewBag.Title = "损益单管理";
}

@Html.Breadcrumb("库存管理", "损益单管理")
@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}


<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="ibox-content m-b-sm border-bottom">
        <div class="row">
            <div class="col-sm-3">
                @Html.SearchTextBox("损益单编号", "AdjustmentOrder")
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <label class="control-label" for="Status">单据状态</label>
                    <select class="form-control m-b" name="Status" id="Status">
                        <option selected>全部</option>
                        <option value="10">新建</option>
                        <option value="20">已审核</option>
                        <option value="-999">已作废</option>
                    </select>
                </div>
            </div>
            <div class="col-sm-3">
                @Html.SearchTextBox("创建人", "CreateUserName")
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <label class="control-label" for="Status">损益类型</label>
                    <select class="form-control m-b" name="Type" id="Type">
                        <option selected>全部</option>
                        <option value="10">损益</option>
                        <option value="20">退货损益</option>
                        <option value="30">移仓损益</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                @Html.SearchTextBox("商品条码", "UPC")
            </div>
            <div class="col-sm-3">
                @Html.SearchTextBox("商品编号", "SkuCode")
            </div>
            <div class="col-sm-3">
                @Html.SearchTextBox("商品名称", "SkuName")
            </div>
            <div class="col-sm-2">
                @Html.SearchTextBox("来源单号", "SourceOrder")
            </div>
            <div class="col-sm-1">
                <button id="btnSearch" class="btn btn-primary" type="button" style="margin-top:25px;float: left; ">查询</button>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                    <table id="gvAjustment" class="table table-striped table-bordered table-hover dataTables-example">
                        <thead>
                            <tr>
                                <th width="5%"><input type="checkbox" id="ckbAll" onclick="gvCheckAll(this);" /></th>
                                <th data-data="AdjustmentOrder">损益单编号</th>
                                <th data-data="StatusName">单据状态</th>
                                <th data-data="TypeName">损益类型</th>
                                <th data-data="SourceOrder">来源单号</th>
                                <th data-data="CreateInfoDisplay">创建时间</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")

    <script>
        var AjustmentMaintain = {
            table: {},
            init: function () {
                var _self = this;

                _self.table = $('#gvAjustment').DataTable({
                    "sAjaxSource": "GetAdjustmentListByPage",
                    "fnServerParams": function (aoData) { //查询条件
                        aoData.push(
                            { "name": "AdjustmentOrder", "value": $("#AdjustmentOrder").val() },
                            { "name": "Status", "value": $("#Status").val() },
                            { "name": "Type", "value": $("#Type").val() },
                            { "name": "CreateUserName", "value": $("#CreateUserName").val() },
                            { "name": "UPC", "value": $("#UPC").val() },
                            { "name": "SkuCode", "value": $("#SkuCode").val() },
                            { "name": "SkuName", "value": $("#SkuName").val() },
                            { "name": "SourceOrder", "value": $("#SourceOrder").val() }
                        );
                    },
                    dom: 'Bfrtip',
                    buttons: [
                        {
                            text: '新增',
                            action: function (e, dt, node, config) {
                                window.location.href = "/Ajustment/AddAjustment";
                            },
                        }
                        , {
                            text: '编辑',
                            action: function (e, dt, node, config) {
                                var sysId = GetGridSysId();
                                if (sysId != null) {

                                    var selectRow = AjustmentMaintain.table.rows(':has(:checkbox:checked)');
                                    if (selectRow.length == 1) {
                                        if (selectRow.data()[0].Status != 10) {
                                            msgAlert("只有新建的损益单才能编辑!");
                                            return;
                                        }
                                        window.location.href = "/Ajustment/UpdateAjustment?sysId=" + sysId;
                                    }
                                }
                            },
                        }
                    ],
                    "columnDefs": [
                        {
                            "targets": 0,
                            "width": "15px",
                            render: function (data, type, full, meta) {
                                return '<input type="checkbox" id="checkbox-all-' + full.SysId + '" value="' + full.SysId + '" />';
                            }
                        },
                        {
                            "targets": 1,
                            "width": "15%",
                            render: function (data, type, full, meta) {
                                return '<a target="_blank" href="/Ajustment/AjustmentView?sysId=' + full.SysId + '">' + full.AdjustmentOrder + '</a>';
                            }
                        }
                    ],
                    "bServerSide": true,
                    "bProcessing": true,
                    "bPaginate": true, //翻页功能
                    "bLengthChange": true, //改变每页显示数据数量
                    "bFilter": false, //过滤功能
                    "bSort": false, //排序功能
                    "bInfo": true, //页脚信息
                    "bAutoWidth": true, //自动宽度
                    "aaSorting": [[2, "Asc"]],
                    "oLanguage": {
                        "sLengthMenu": "每页显示 _MENU_ 条记录",
                        "sInfo": "从 _START_ 到 _END_ /共 _TOTAL_ 条数据",
                        "sInfoEmpty": "",
                        "sInfoFiltered": "(从 _MAX_ 条数据中检索)",
                        "oPaginate": {
                            "sFirst": "首页",
                            "sPrevious": "前一页",
                            "sNext": "后一页",
                            "sLast": "尾页"
                        },
                        "sZeroRecords": "没有检索到数据"
                    }
                });

                $("#btnSearch").bind("click", function () { //按钮 触发table重新请求服务器
                    AjustmentMaintain.table.ajax.reload();
                });

            }
        }

        $(function () {
            AjustmentMaintain.init();
        })


    </script>
}

Repos/WMSPortal/NBK.WMS.Portal/Views/Ajustment/AjustmentView.cshtml
@using NBK.WMS.Portal.Helpers
@model NBK.ECService.WMS.DTO.AdjustmentViewDto

@{
    ViewBag.Title = "损益单明细";
}

@Html.Breadcrumb("损益单管理", "/Ajustment/AjustmentMaintain", "损益单明细")

@section Styles {
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
}

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div id="AjustmentView" class="ibox-content m-b-sm border-bottom">

        <form id="AjustmentForm" class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label ">
                    <H2 style="color: red;text-align:left">损益明细</H2>
                </label>

                <div class="col-sm-7">

                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-7">
                        </div>
                        <div class="col-sm-5" id="divBarCode">
                        </div>

                        <div class="col-sm-3">

                        </div>
                        <div class="col-sm-8 font-italic" style="text-align:right" id="divBarCodeValue">@Model.AdjustmentOrder</div>
                        <div class="col-sm-1">

                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group   hr-line-dashed"></div>

            <div class="form-group">
                <div class="col-sm-1">
                    损益类型:
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-12"> @Model.TypeName </div>
                        <div class="col-sm-12 hr-line-dashed" style="margin-top: 5px"> </div>
                    </div>
                </div>
                <div class="col-sm-1">
                    损益单号:
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-12"> @Model.AdjustmentOrder </div>
                        <div class="col-sm-12 hr-line-dashed" style="margin-top: 5px"> </div>
                    </div>
                </div>
                <div class="col-sm-1">
                    来源单号:
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-12"> @Model.SourceOrder</div>
                        <div class="col-sm-12 hr-line-dashed" style="margin-top: 5px"> </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-1">
                    创建时间:
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-12"> @Model.CreateInfoDisplay</div>
                        <div class="col-sm-12 hr-line-dashed" style="margin-top: 5px"> </div>
                    </div>
                </div>
                <div class="col-sm-1">
                    仓库:
                </div>
                <div class="col-sm-3">
                    <div class="row">
                        <div class="col-sm-12"> @Model.WareHouseName </div>
                        <div class="col-sm-12 hr-line-dashed" style="margin-top: 5px"> </div>
                    </div>
                </div>
            </div>

            <div class="form-group   hr-line-dashed"></div>

            <div class="form-group ">
                <label class="col-sm-2 control-label" style="text-align:left;">商品明细</label>
                <div class="col-sm-10"></div>

                <div class="col-sm-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>序号</th>
                                <th>商品编号</th>
                                <th>商品名称</th>
                                <th>商品描述</th>
                                <th>商品条码</th>
                                <th>单位</th>
                                <th>货位</th>
                                <th>批次</th>
                                <th>托盘</th>
                                <th>渠道</th>
                                <th>损益级别</th>
                                <th>损益数量</th>
                                <th>备注</th>
                                <th>图片</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var index = 0;
                                foreach (var info in Model.AdjustmentDetailList)
                                {
                                    index++;
                                    <tr>
                                        <td>@index</td>
                                        <td>@info.SkuCode</td>
                                        <td>@info.SkuName</td>
                                        <td>@info.SkuDescr</td>
                                        <td>@info.UPC</td>
                                        <td>@info.UOMCode</td>
                                        <td>@info.Loc</td>
                                        <td>@info.Lot</td>
                                        <td>@info.Lpn</td>
                                        <td>@info.Channel</td>
                                        <td>@info.AdjustlevelDisplay</td>
                                        <td>@info.DisplayQty</td>
                                        <td>@info.Remark</td>
                                        <td>
                                            @if (info.PictureDtoList != null && info.PictureDtoList.Count > 0)
                                            {
                                                foreach (var item in info.PictureDtoList)
                                                {
                                                    <span style="margin-left:5px;" class="fileinput-filename"><a href="@item.ShowUrl" target="_blank">@item.Name</a></span>
                                                }
                                            }
                                        </td>
                                    </tr>
                                }
                            }

                        </tbody>
                    </table>
                </div>

            </div>

            <div class="ibox-footer text-right tooltip-demo">
                @if ((bool)ViewData["IsAuditDisplay"])
                {
                    <a class="btn btn-sm btn-primary" id="btnAudit"><i class="fa fa-check-square-o"></i> 审核</a>
                }

                <a class="btn btn-white btn-sm" id="btnReturn"><i class="fa fa-times"></i> 返回</a>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/plugins/barcode")
    <script type="text/javascript">

        $(document).ready(function () {
            $("#divBarCode").empty().barcode($("#divBarCodeValue").html(), "code128", { barWidth: 1, barHeight: 45, showHRI: false });

            $("#btnReturn").click(function () {
                backParentPage();
            });

            $("#btnAudit").click(function () {
                var request = {
                    SysId: '@Model.SysId'
                };
                saveLoading('show');
                $.ajax({
                    url: "@Url.Action("Audit", "Ajustment")",
                    data: request,
                    type: "post",
                    success: function (data) {
                        saveLoading();
                        if (data.success) {
                            msgSuccess("审核成功!");
                            backParentPage();
                        }
                        else {
                            msgErro(data.message);
                        }
                    },
                    error: function () {
                        saveLoading();
                        msgErro("操作失败！");
                    }
                });

            });
        });

        var backParentPage = function () {
            window.location.href = '@Url.Action("AjustmentMaintain", "Ajustment")';
        };

    </script>
}